branches:
  only:
    - source
    
environment:
  access_token:
    # The encrypted version of your GitHub access token
    secure: +GR3AE0ogaWclY3rqE1yrwtK76xSY885x4Y1Oy4VkBJVpljl9m3iaAtYWv3pE3Nx

install:
  - git submodule update --init --recursive
  - mkdir ..\Wyam
  - mkdir ..\output
  # Fetch the latest version of Wyam 
  - "curl -s https://raw.githubusercontent.com/Wyamio/Wyam/master/RELEASE -o ..\\Wyam\\wyamversion.txt"
  - set /P WYAMVERSION=< ..\Wyam\wyamversion.txt
  - echo %WYAMVERSION%
  # Get and unzip the latest version of Wyam
  - ps: Start-FileDownload "https://github.com/Wyamio/Wyam/releases/download/$env:WYAMVERSION/Wyam-$env:WYAMVERSION.zip" -FileName "..\Wyam\Wyam.zip"
  - 7z x ..\Wyam\Wyam.zip -o..\Wyam -r

build_script:
  - ..\Wyam\wyam --recipe Blog --theme CleanBlog --output ..\output

on_success:
  # Switch branches to master, clean the folder, copy everything in from the Wyam output, and commit/push
  # See http://www.appveyor.com/docs/how-to/git-push for more info
  - git config --global credential.helper store
  # your Git email and name
  - git config --global user.email "ojikeii@gmail.com"
  - git config --global user.name "ojikeii"
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
  - git checkout master
  - xcopy README.md ..\output\
  - git rm -rf .
  - xcopy ..\output . /E
  # your domain name or remove if not using a custom domain
  - echo ojikeii.net > CNAME
  # the origin of your repository - have to reset it here because AppVeyor pulls from SSH, but GitHub won't accept SSH pushes
  - git remote set-url origin https://github.com/ojikeii/ojikeii.github.io.git
  - git add -A
  - git commit -a -m "Commit from AppVeyor"
  - git push